#===============================================================================
#
#     Modal Tool Kit (MTK)
#
#     Copyright 2017-2020 Christopher A. Lupp
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
#===============================================================================
language: python

python:
  - "3.6"

os:
  - linux
  # - osx


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-9
    - g++-9
  # homebrew:
  #   packages:
  #   - cmake
  #   - gcc-9
  #   - g++-9
  #   update: true


before_script:
  - git clone https://github.com/eigenteam/eigen-git-mirror.git
  - cd eigen-git-mirror
  - git checkout 3.3.4
  - export EIGEN3_ROOT=$PWD
  - cd ..
  - echo $EIGEN3_ROOT > Environment.config
  - export CC=gcc-9
  - export CXX=g++-9

script:
  - pip install .
  - cd test
  - python eigenpair.py
  - python modeset.py
  # - python modetracking.py